version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nycbuswatcher-gtfsrt-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ll3d7xend2xd"
s3_prefix = "nycbuswatcher-gtfsrt-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
